jobs:
  install-node:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: latest
      - run: node --version

orbs:
  node: circleci/node@2.0.2

version: 2.1

workflows:
  test-jobs:
    jobs:
      - install-node
  matrix-tests:
    jobs:
      - node/test:
          version: 13.11.0
      - node/test:
          version: 12.16.0
      - node/test:
          version: 10.19.0
  deploy-heroku:
    jobs:
      - heroku/deploy-via-git:
      filters:
        branches:
          only:
            - master
      requires:
        - matrix-tests