version: 2.1

orbs:
  slack: circleci/slack@4.5.0

jobs:
  imajob:
    docker:
      - image: cimg/node:17.1.0  
    steps:
      - checkout
      - run:
          name: echo hi
          command: echo "hi"
      - slack/notify

workflows:
    version: 2
    imaworkflow:
      triggers:
        - schedule:
            cron: "0 0 * * *"       
            filters:
              branches:
                only:
                  - main        
      jobs:
        - imajob
    